apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: andy-braren-pacman
    appstudio.openshift.io/component: devfile-sample-xfpf
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: devfile-sample-xfpf
  namespace: abrarenrh-tenant
spec:
  url: https://github.com/font/k8s-example-apps/tree/master/pacman-nodejs-app
